api-key: JmsPull 接口 key
domain-sub-link: '错误: 尚未初始化'
domain-sub-link-update-time: "2022-06-14 17:58:00"
ip-sub-link: '错误: 尚未初始化'
ip-sub-link-update-time: "2022-06-14 17:58:00"
jms-id: jms-sub-id
jms-server: jms-sub-server
